version: '3.8'

services:
  ethereum-node:
    image: ethereum/client-go:latest
    command: geth --syncmode light --rpc --rpcaddr 0.0.0.0 --rpcport 8545 --rpcapi eth,net,web3
    ports:
      - "8545:8545"
    volumes:
      - volumes/ethereum-data:/root/.ethereum
    container_name: ethereum_light_node
    networks:
      - mynetwork

  python-app:
    build: ./scanner
    volumes:
      - volumes/scanner-data:/app
    environment:
      ETHERSCAN_API_KEY: ${ETHERSCAN_API_KEY}
      UNISWAPV2ROUTER_CONTRACT_ADDRESS: ${UNISWAPV2ROUTER_CONTRACT_ADDRESS}
      ADDRESS_TO_TRACK: ${ADDRESS_TO_TRACK}
    container_name: python_app_container
    networks:
      - mynetwork
    depends_on:
      - ethereum-node

networks:
  mynetwork:
    driver: bridge